name: Run DBT and Push Updated Database

on:
  # schedule:
  #   - cron: '0 19 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-dbt:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dbt
        working-directory: ./data_model
        run: |
          for i in {1..3}; do
            dbt run --target prod && break || echo "Retrying ($i/3)..."
            sleep 10
          done
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data_model/prod.duckdb
          git commit -m "Update prod.duckdb after successful dbt run on $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git push origin main
